### PR TITLE
Update download_trust_data

### PR DESCRIPTION
**Pull request by sophiemeakin**
From 29 April 2021, raw data is now split between two files before/after 06 April 2021

### CODE REVIEW

**Comment by sophiemeakin** [comment]
Current fix doesn't work for historical values of `release_date`.

**Review by seabbs — APPROVED** [review]
LGTM

**Comment by sophiemeakin** [comment]
Need to update the past file name again - looks like it will just be at a static URL and not update with new data releases.

**Comment by seabbs** [comment]
Is this ready for merge? Rt is still pulling from master and therefore falling over I think.

**Pull request merged**
